### ISSUE TITLE
Adicionar documentação de Geração de Migration

### ISSUE THREAD

**Issue by KelvynSinhorini** [DeveloperFabricio/HotelBookings#1]
Olá, Fabricio!! Muito interessante e muito bem desenvolvido seu projeto!! Caso aceite sugestões, na documentação ficaria legal adicionar a forma de geração de migration...

**Comment by DeveloperFabricio** [comment]
Muito bem pensado, estou desenvolvendo mais projetos e vou fazer isso que você falou, e também aqui no HotelBookings, obrigado pela contribuição, é muito bem vinda.
